### ISSUE TITLE
Parsing fails on extra Flags entry with xsi:nil=true

### ISSUE THREAD

**Issue by winbow13** [maddymakesgames/celeste_rs#1]
I have two saves, a vanilla one and modded one. On upload to the website, the modded one seems to work fine, while the vanilla one tells me "Errors found when parsing save file: missing field `$text`." My debug one also works fine, so I'm wondering if some bug got introduced when adding mod parsers to vanilla save files.

**Comment by maddymakesgames** [comment]
hmm, could you upload your save? I did mainly test on modded saves so itd make sense for some vanilla saves to be broken.

**Comment by winbow13** [comment]
[0.txt](https://github.com/maddymakesgames/celeste_rs/files/15419864/0.txt)
[2.txt](https://github.com/maddymakesgames/celeste_rs/files/15419865/2.txt)

0 is my vanilla file, 2 is my modded file, I changed them from .celeste to .txt files to upload them, you should probably change them back lol

**Comment by maddymakesgames** [comment]
It seems like your `Flags` field has an extra entry that is `xsi:nil`. I had no idea this was possible lol. I'll try to add edge case detection for this.

**Comment by maddymakesgames** [comment]
fixed in e768902
will be in next version release
